#name, main, version and api are required
name: ServerMail
main: tschrock\ServerMail\ServerMail
version: 1.0.0-BETA
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]

load: POSTWORLD
author: tschrock (tschrock123@gmail.com)
description: Mail for your server! :D
website: http://www.tschrock.net
commands:
 mail:
  description: "Sends mail to other players."
  usage: "/mail < read | clear | send | sendall >"
  permission: tschrock.servermail.command.mail
permissions:
 tschrock.servermail.command.mail:
  description: "Allows the user to run the mail command"
  default: true
 tschrock.servermail.command.mail.all:
  description: "Allows the user to send a message to all players"
  default: op
